# Generated by Django 5.1.6 on 2025-02-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='task',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
