# Generated by Django 5.1.6 on 2025-02-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_request_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email_team',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
